version: '3.9'

services:
  server:
    ports:
      - 5336:8080
    container_name: moneytrail-api
    networks:
      - nginx-proxy-manager_default
    restart: always
    build: .

networks:
  nginx-proxy-manager_default:
    external: true
