export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ADD_SHOP = "ADD_SHOP";
export const DELETE_SHOPS = "DELETE_SHOPS";
export const GET_SHOPS = "GET_SHOPS";
export const SHOPS_LOADING = "SHOPS_LOADING";
export const GET_SHOPS_ALL = "GET_SHOPS_ALL";

export const ADD_USER_TRANSACTION = "ADD_USER_TRANSACTION";
export const DELETE_USER_TRANSACTION = "DELETE_USER_TRANSACTION";
export const GET_USER_TRANSACTIONS = "GET_USER_TRANSACTIONS";
export const USER_TRANSACTIONS_LOADING = "USER_TRANSACTIONS_LOADING";
