export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_SHOP = 'ADD_SHOP';
export const DELETE_SHOPS = 'DELETE_SHOPS';
export const GET_SHOPS = 'GET_SHOPS';
export const SHOPS_LOADING = 'SHOPS_LOADING';
export const GET_SHOPS_ALL = 'GET_SHOPS_ALL';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';

export const GET_TICKER_DATA = 'GET_TICKER_DATA';
export const TICKER_DATA_LOADING = 'TICKER_DATA_LOADING';
export const GET_SEARCH_DATA = 'GET_SEARCH_DATA';
export const SEARCH_DATA_LOADING = 'SEARCH_DATA_LOADING';
export const GET_HISTORICAL_DATA = 'GET_HISTORICAL_DATA';
export const HISTORICAL_DATA_LOADING = 'HISTORICAL_DATA_LOADING';

export const ADD_INVESTMENT = 'ADD_INVESTMENT';
export const DELETE_INVESTMENT = 'DELETE_INVESTMENT';
export const GET_INVESTMENTS = 'GET_INVESTMENTS';
export const INVESTMENTS_LOADING = 'INVESTMENTS_LOADING';
